//
//  XGLRenderPassDepthAttachment.h
//  XGL
//
//  Created by jacques tronconi on 15/07/2021.
//

#ifndef __XGL_RENDERPASSDEPTHATTTACHMENT_H__
#define __XGL_RENDERPASSDEPTHATTTACHMENT_H__

#include "XGLRenderPassAttachment.h"
#include "XGLMultisampleDepthResolveFilter.h"

namespace XGL
{
    /**
     *  @brief A depth render target that serves as the output destination for depth
     *  pixels generated by a render pass.
     *
     */
    struct RenderPassDepthAttachment : public RenderPassAttachment
    {
        //! @brief The depth to use when clearing the depth attachment.
        float clearDepth = 1.0f;
        
        //! @brief The filter used for an MSAA depth resolve operation.
        MultisampleDepthResolveFilter depthResolveFilter = MultisampleDepthResolveFilter::Sample0;
    };
}

#endif /* __XGL_RENDERPASSDEPTHATTTACHMENT_H__ */
