//
//  XGLRenderPassStencilAttachment.h
//  XGL
//
//  Created by jacques tronconi on 15/07/2021.
//

#ifndef __XGL_RENDERPASSSTENCILATTACHMENT_H__
#define __XGL_RENDERPASSSTENCILATTACHMENT_H__

#include "XGLRenderPassAttachment.h"
#include "XGLMultisampleStencilResolveFilter.h"

namespace XGL
{
    /**
     *  @brief A stencil render target that serves as the output destination for
     *  stencil pixels generated by a render pass.
     *
     */
    struct RenderPassStencilAttachment : public RenderPassAttachment
    {
        //! @brief The value to use when clearing the stencil attachment.
        size_t clearStencil = 0;
        
        //! @brief The filter used for stencil multisample resolve.
        MultisampleStencilResolveFilter stencilResolveFilter = MultisampleStencilResolveFilter::Sample0;
    };
}

#endif /* __XGL_RENDERPASSSTENCILATTACHMENT_H__ */
