//
//  XGLRenderPassColorAttachment.h
//  XGL
//
//  Created by jacques tronconi on 15/07/2021.
//

#ifndef __XGL_RENDERPASSCOLORATTACHMENT_H__
#define __XGL_RENDERPASSCOLORATTACHMENT_H__

#include "XGLRenderPassAttachment.h"

namespace XGL
{
    /**
     *  @brief A color render target that serves as the output destination for color
     *  pixels generated by a render pass.
     *
     */
    struct RenderPassColorAttachment : public RenderPassAttachment
    {
        //! @brief The color to use when clearing the color attachment.
        glm::vec4 clearColor = { 0.0f, 0.0f, 0.0f, 1.0f };
    };
}

#endif /* __XGL_RENDERPASSCOLORATTACHMENT_H__ */
